default_language_version:
    python: python3

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/omnilib/ufmt
    rev: v1.3.0
    hooks:
      -   id: ufmt
          additional_dependencies:
          -   black == 20.8b0
          -   usort == 0.6.3
